version: '3.8'

services:
  # O serviço 'app' é o seu ambiente de desenvolvimento principal.
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity

  # O serviço 'db' é o seu banco de dados PostgreSQL.
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskmaster_db
    ports:
      - '5432:5432'